INSERT INTO pays VALUES (NULL,'AF', 'Afghanistan');
INSERT INTO pays VALUES (NULL,'ZA', 'Afrique du Sud');
INSERT INTO pays VALUES (NULL,'AL', 'Albanie');
INSERT INTO pays VALUES (NULL,'DZ', 'Algérie');
INSERT INTO pays VALUES (NULL,'DE', 'Allemagne');
INSERT INTO pays VALUES (NULL,'AD', 'Andorre');
INSERT INTO pays VALUES (NULL,'AO', 'Angola');
INSERT INTO pays VALUES (NULL,'AI', 'Anguilla');
INSERT INTO pays VALUES (NULL,'AQ', 'Antarctique');
INSERT INTO pays VALUES (NULL,'AG', 'Antigua-et-Barbuda');
INSERT INTO pays VALUES (NULL,'SA', 'Arabie saoudite');
INSERT INTO pays VALUES (NULL,'AR', 'Argentine');
INSERT INTO pays VALUES (NULL,'AM', 'Arménie');
INSERT INTO pays VALUES (NULL,'AW', 'Aruba');
INSERT INTO pays VALUES (NULL,'AU', 'Australie');
INSERT INTO pays VALUES (NULL,'AT', 'Autriche');
INSERT INTO pays VALUES (NULL,'AZ', 'Azerbaïdjan');
INSERT INTO pays VALUES (NULL,'BS', 'Bahamas');
INSERT INTO pays VALUES (NULL,'BH', 'Bahreïn');
INSERT INTO pays VALUES (NULL,'BD', 'Bangladesh');
INSERT INTO pays VALUES (NULL,'BB', 'Barbade');
INSERT INTO pays VALUES (NULL,'BE', 'Belgique');
INSERT INTO pays VALUES (NULL,'BZ', 'Belize');
INSERT INTO pays VALUES (NULL,'BJ', 'Bénin');
INSERT INTO pays VALUES (NULL,'BM', 'Bermudes');
INSERT INTO pays VALUES (NULL,'BT', 'Bhoutan');
INSERT INTO pays VALUES (NULL,'BY', 'Biélorussie');
INSERT INTO pays VALUES (NULL,'BO', 'Bolivie');
INSERT INTO pays VALUES (NULL,'BA', 'Bosnie-Herzégovine');
INSERT INTO pays VALUES (NULL,'BW', 'Botswana');
INSERT INTO pays VALUES (NULL,'BR', 'Brésil');
INSERT INTO pays VALUES (NULL,'BN', 'Brunéi Darussalam');
INSERT INTO pays VALUES (NULL,'BG', 'Bulgarie');
INSERT INTO pays VALUES (NULL,'BF', 'Burkina Faso');
INSERT INTO pays VALUES (NULL,'BI', 'Burundi');
INSERT INTO pays VALUES (NULL,'KH', 'Cambodge');
INSERT INTO pays VALUES (NULL,'CM', 'Cameroun');
INSERT INTO pays VALUES (NULL,'CA', 'Canada');
INSERT INTO pays VALUES (NULL,'CV', 'Cap-Vert');
INSERT INTO pays VALUES (NULL,'EA', 'Ceuta et Melilla');
INSERT INTO pays VALUES (NULL,'CL', 'Chili');
INSERT INTO pays VALUES (NULL,'CN', 'Chine');
INSERT INTO pays VALUES (NULL,'CY', 'Chypre');
INSERT INTO pays VALUES (NULL,'CO', 'Colombie');
INSERT INTO pays VALUES (NULL,'KM', 'Comores');
INSERT INTO pays VALUES (NULL,'CG', 'Congo-Brazzaville');
INSERT INTO pays VALUES (NULL,'CD', 'Congo-Kinshasa');
INSERT INTO pays VALUES (NULL,'KP', 'Corée du Nord');
INSERT INTO pays VALUES (NULL,'KR', 'Corée du Sud');
INSERT INTO pays VALUES (NULL,'CR', 'Costa Rica');
INSERT INTO pays VALUES (NULL,'CI', 'Côte d’Ivoire');
INSERT INTO pays VALUES (NULL,'HR', 'Croatie');
INSERT INTO pays VALUES (NULL,'CU', 'Cuba');
INSERT INTO pays VALUES (NULL,'CW', 'Curaçao');
INSERT INTO pays VALUES (NULL,'DK', 'Danemark');
INSERT INTO pays VALUES (NULL,'DG', 'Diego Garcia');
INSERT INTO pays VALUES (NULL,'DJ', 'Djibouti');
INSERT INTO pays VALUES (NULL,'DM', 'Dominique');
INSERT INTO pays VALUES (NULL,'EG', 'Égypte');
INSERT INTO pays VALUES (NULL,'SV', 'El Salvador');
INSERT INTO pays VALUES (NULL,'AE', 'Émirats arabes unis');
INSERT INTO pays VALUES (NULL,'EC', 'Équateur');
INSERT INTO pays VALUES (NULL,'ER', 'Érythrée');
INSERT INTO pays VALUES (NULL,'ES', 'Espagne');
INSERT INTO pays VALUES (NULL,'EE', 'Estonie');
INSERT INTO pays VALUES (NULL,'VA', 'État de la Cité du Vatican');
INSERT INTO pays VALUES (NULL,'FM', 'États fédérés de Micronésie');
INSERT INTO pays VALUES (NULL,'US', 'États-Unis');
INSERT INTO pays VALUES (NULL,'ET', 'Éthiopie');
INSERT INTO pays VALUES (NULL,'EZ', 'Eurozone');
INSERT INTO pays VALUES (NULL,'FJ', 'Fidji');
INSERT INTO pays VALUES (NULL,'FI', 'Finlande');
INSERT INTO pays VALUES (NULL,'FR', 'France');
INSERT INTO pays VALUES (NULL,'GA', 'Gabon');
INSERT INTO pays VALUES (NULL,'GM', 'Gambie');
INSERT INTO pays VALUES (NULL,'GE', 'Géorgie');
INSERT INTO pays VALUES (NULL,'GS', 'Géorgie du Sud et îles Sandwich du Sud');
INSERT INTO pays VALUES (NULL,'GH', 'Ghana');
INSERT INTO pays VALUES (NULL,'GI', 'Gibraltar');
INSERT INTO pays VALUES (NULL,'GR', 'Grèce');
INSERT INTO pays VALUES (NULL,'GD', 'Grenade');
INSERT INTO pays VALUES (NULL,'GL', 'Groenland');
INSERT INTO pays VALUES (NULL,'GP', 'Guadeloupe');
INSERT INTO pays VALUES (NULL,'GU', 'Guam');
INSERT INTO pays VALUES (NULL,'GT', 'Guatemala');
INSERT INTO pays VALUES (NULL,'GG', 'Guernesey');
INSERT INTO pays VALUES (NULL,'GN', 'Guinée');
INSERT INTO pays VALUES (NULL,'GQ', 'Guinée équatoriale');
INSERT INTO pays VALUES (NULL,'GW', 'Guinée-Bissau');
INSERT INTO pays VALUES (NULL,'GY', 'Guyana');
INSERT INTO pays VALUES (NULL,'GF', 'Guyane française');
INSERT INTO pays VALUES (NULL,'HT', 'Haïti');
INSERT INTO pays VALUES (NULL,'HN', 'Honduras');
INSERT INTO pays VALUES (NULL,'HU', 'Hongrie');
INSERT INTO pays VALUES (NULL,'CX', 'Île Christmas');
INSERT INTO pays VALUES (NULL,'AC', 'Île de l’Ascension');
INSERT INTO pays VALUES (NULL,'IM', 'Île de Man');
INSERT INTO pays VALUES (NULL,'NF', 'Île Norfolk');
INSERT INTO pays VALUES (NULL,'AX', 'Îles Åland');
INSERT INTO pays VALUES (NULL,'KY', 'Îles Caïmans');
INSERT INTO pays VALUES (NULL,'IC', 'Îles Canaries');
INSERT INTO pays VALUES (NULL,'CC', 'Îles Cocos');
INSERT INTO pays VALUES (NULL,'CK', 'Îles Cook');
INSERT INTO pays VALUES (NULL,'FO', 'Îles Féroé');
INSERT INTO pays VALUES (NULL,'FK', 'Îles Malouines');
INSERT INTO pays VALUES (NULL,'MP', 'Îles Mariannes du Nord');
INSERT INTO pays VALUES (NULL,'MH', 'Îles Marshall');
INSERT INTO pays VALUES (NULL,'UM', 'Îles mineures éloignées des États-Unis');
INSERT INTO pays VALUES (NULL,'PN', 'Îles Pitcairn');
INSERT INTO pays VALUES (NULL,'SB', 'Îles Salomon');
INSERT INTO pays VALUES (NULL,'TC', 'Îles Turques-et-Caïques');
INSERT INTO pays VALUES (NULL,'VG', 'Îles Vierges britanniques');
INSERT INTO pays VALUES (NULL,'VI', 'Îles Vierges des États-Unis');
INSERT INTO pays VALUES (NULL,'IN', 'Inde');
INSERT INTO pays VALUES (NULL,'ID', 'Indonésie');
INSERT INTO pays VALUES (NULL,'IQ', 'Irak');
INSERT INTO pays VALUES (NULL,'IR', 'Iran');
INSERT INTO pays VALUES (NULL,'IE', 'Irlande');
INSERT INTO pays VALUES (NULL,'IS', 'Islande');
INSERT INTO pays VALUES (NULL,'IL', 'Israël');
INSERT INTO pays VALUES (NULL,'IT', 'Italie');
INSERT INTO pays VALUES (NULL,'JM', 'Jamaïque');
INSERT INTO pays VALUES (NULL,'JP', 'Japon');
INSERT INTO pays VALUES (NULL,'JE', 'Jersey');
INSERT INTO pays VALUES (NULL,'JO', 'Jordanie');
INSERT INTO pays VALUES (NULL,'KZ', 'Kazakhstan');
INSERT INTO pays VALUES (NULL,'KE', 'Kenya');
INSERT INTO pays VALUES (NULL,'KG', 'Kirghizistan');
INSERT INTO pays VALUES (NULL,'KI', 'Kiribati');
INSERT INTO pays VALUES (NULL,'XK', 'Kosovo');
INSERT INTO pays VALUES (NULL,'KW', 'Koweït');
INSERT INTO pays VALUES (NULL,'RE', 'La Réunion');
INSERT INTO pays VALUES (NULL,'LA', 'Laos');
INSERT INTO pays VALUES (NULL,'LS', 'Lesotho');
INSERT INTO pays VALUES (NULL,'LV', 'Lettonie');
INSERT INTO pays VALUES (NULL,'LB', 'Liban');
INSERT INTO pays VALUES (NULL,'LR', 'Libéria');
INSERT INTO pays VALUES (NULL,'LY', 'Libye');
INSERT INTO pays VALUES (NULL,'LI', 'Liechtenstein');
INSERT INTO pays VALUES (NULL,'LT', 'Lituanie');
INSERT INTO pays VALUES (NULL,'LU', 'Luxembourg');
INSERT INTO pays VALUES (NULL,'MK', 'Macédoine');
INSERT INTO pays VALUES (NULL,'MG', 'Madagascar');
INSERT INTO pays VALUES (NULL,'MY', 'Malaisie');
INSERT INTO pays VALUES (NULL,'MW', 'Malawi');
INSERT INTO pays VALUES (NULL,'MV', 'Maldives');
INSERT INTO pays VALUES (NULL,'ML', 'Mali');
INSERT INTO pays VALUES (NULL,'MT', 'Malte');
INSERT INTO pays VALUES (NULL,'MA', 'Maroc');
INSERT INTO pays VALUES (NULL,'MQ', 'Martinique');
INSERT INTO pays VALUES (NULL,'MU', 'Maurice');
INSERT INTO pays VALUES (NULL,'MR', 'Mauritanie');
INSERT INTO pays VALUES (NULL,'YT', 'Mayotte');
INSERT INTO pays VALUES (NULL,'MX', 'Mexique');
INSERT INTO pays VALUES (NULL,'MD', 'Moldavie');
INSERT INTO pays VALUES (NULL,'MC', 'Monaco');
INSERT INTO pays VALUES (NULL,'MN', 'Mongolie');
INSERT INTO pays VALUES (NULL,'ME', 'Monténégro');
INSERT INTO pays VALUES (NULL,'MS', 'Montserrat');
INSERT INTO pays VALUES (NULL,'MZ', 'Mozambique');
INSERT INTO pays VALUES (NULL,'MM', 'Myanmar (NULL,Birmanie)');
INSERT INTO pays VALUES (NULL,'NA', 'Namibie');
INSERT INTO pays VALUES (NULL,'UN', 'Nations Unies');
INSERT INTO pays VALUES (NULL,'NR', 'Nauru');
INSERT INTO pays VALUES (NULL,'NP', 'Népal');
INSERT INTO pays VALUES (NULL,'NI', 'Nicaragua');
INSERT INTO pays VALUES (NULL,'NE', 'Niger');
INSERT INTO pays VALUES (NULL,'NG', 'Nigéria');
INSERT INTO pays VALUES (NULL,'NU', 'Niue');
INSERT INTO pays VALUES (NULL,'NO', 'Norvège');
INSERT INTO pays VALUES (NULL,'NC', 'Nouvelle-Calédonie');
INSERT INTO pays VALUES (NULL,'NZ', 'Nouvelle-Zélande');
INSERT INTO pays VALUES (NULL,'OM', 'Oman');
INSERT INTO pays VALUES (NULL,'UG', 'Ouganda');
INSERT INTO pays VALUES (NULL,'UZ', 'Ouzbékistan');
INSERT INTO pays VALUES (NULL,'PK', 'Pakistan');
INSERT INTO pays VALUES (NULL,'PW', 'Palaos');
INSERT INTO pays VALUES (NULL,'PA', 'Panama');
INSERT INTO pays VALUES (NULL,'PG', 'Papouasie-Nouvelle-Guinée');
INSERT INTO pays VALUES (NULL,'PY', 'Paraguay');
INSERT INTO pays VALUES (NULL,'NL', 'Pays-Bas');
INSERT INTO pays VALUES (NULL,'BQ', 'Pays-Bas caribéens');
INSERT INTO pays VALUES (NULL,'PE', 'Pérou');
INSERT INTO pays VALUES (NULL,'PH', 'Philippines');
INSERT INTO pays VALUES (NULL,'PL', 'Pologne');
INSERT INTO pays VALUES (NULL,'PF', 'Polynésie française');
INSERT INTO pays VALUES (NULL,'PR', 'Porto Rico');
INSERT INTO pays VALUES (NULL,'PT', 'Portugal');
INSERT INTO pays VALUES (NULL,'QA', 'Qatar');
INSERT INTO pays VALUES (NULL,'HK', 'R.A.S. chinoise de Hong Kong');
INSERT INTO pays VALUES (NULL,'MO', 'R.A.S. chinoise de Macao');
INSERT INTO pays VALUES (NULL,'CF', 'République centrafricaine');
INSERT INTO pays VALUES (NULL,'DO', 'République dominicaine');
INSERT INTO pays VALUES (NULL,'RO', 'Roumanie');
INSERT INTO pays VALUES (NULL,'GB', 'Royaume-Uni');
INSERT INTO pays VALUES (NULL,'RU', 'Russie');
INSERT INTO pays VALUES (NULL,'RW', 'Rwanda');
INSERT INTO pays VALUES (NULL,'EH', 'Sahara occidental');
INSERT INTO pays VALUES (NULL,'BL', 'Saint-Barthélemy');
INSERT INTO pays VALUES (NULL,'KN', 'Saint-Christophe-et-Niévès');
INSERT INTO pays VALUES (NULL,'SM', 'Saint-Marin');
INSERT INTO pays VALUES (NULL,'MF', 'Saint-Martin');
INSERT INTO pays VALUES (NULL,'SX', 'Saint-Martin (NULL,partie néerlandaise)');
INSERT INTO pays VALUES (NULL,'PM', 'Saint-Pierre-et-Miquelon');
INSERT INTO pays VALUES (NULL,'VC', 'Saint-Vincent-et-les-Grenadines');
INSERT INTO pays VALUES (NULL,'SH', 'Sainte-Hélène');
INSERT INTO pays VALUES (NULL,'LC', 'Sainte-Lucie');
INSERT INTO pays VALUES (NULL,'WS', 'Samoa');
INSERT INTO pays VALUES (NULL,'AS', 'Samoa américaines');
INSERT INTO pays VALUES (NULL,'ST', 'Sao Tomé-et-Principe');
INSERT INTO pays VALUES (NULL,'SN', 'Sénégal');
INSERT INTO pays VALUES (NULL,'RS', 'Serbie');
INSERT INTO pays VALUES (NULL,'SC', 'Seychelles');
INSERT INTO pays VALUES (NULL,'SL', 'Sierra Leone');
INSERT INTO pays VALUES (NULL,'SG', 'Singapour');
INSERT INTO pays VALUES (NULL,'SK', 'Slovaquie');
INSERT INTO pays VALUES (NULL,'SI', 'Slovénie');
INSERT INTO pays VALUES (NULL,'SO', 'Somalie');
INSERT INTO pays VALUES (NULL,'SD', 'Soudan');
INSERT INTO pays VALUES (NULL,'SS', 'Soudan du Sud');
INSERT INTO pays VALUES (NULL,'LK', 'Sri Lanka');
INSERT INTO pays VALUES (NULL,'SE', 'Suède');
INSERT INTO pays VALUES (NULL,'CH', 'Suisse');
INSERT INTO pays VALUES (NULL,'SR', 'Suriname');
INSERT INTO pays VALUES (NULL,'SJ', 'Svalbard et Jan Mayen');
INSERT INTO pays VALUES (NULL,'SZ', 'Swaziland');
INSERT INTO pays VALUES (NULL,'SY', 'Syrie');
INSERT INTO pays VALUES (NULL,'TJ', 'Tadjikistan');
INSERT INTO pays VALUES (NULL,'TW', 'Taïwan');
INSERT INTO pays VALUES (NULL,'TZ', 'Tanzanie');
INSERT INTO pays VALUES (NULL,'TD', 'Tchad');
INSERT INTO pays VALUES (NULL,'CZ', 'Tchéquie');
INSERT INTO pays VALUES (NULL,'TF', 'Terres australes françaises');
INSERT INTO pays VALUES (NULL,'IO', 'Territoire britannique de l’océan Indien');
INSERT INTO pays VALUES (NULL,'PS', 'Territoires palestiniens');
INSERT INTO pays VALUES (NULL,'TH', 'Thaïlande');
INSERT INTO pays VALUES (NULL,'TL', 'Timor oriental');
INSERT INTO pays VALUES (NULL,'TG', 'Togo');
INSERT INTO pays VALUES (NULL,'TK', 'Tokélaou');
INSERT INTO pays VALUES (NULL,'TO', 'Tonga');
INSERT INTO pays VALUES (NULL,'TT', 'Trinité-et-Tobago');
INSERT INTO pays VALUES (NULL,'TA', 'Tristan da Cunha');
INSERT INTO pays VALUES (NULL,'TN', 'Tunisie');
INSERT INTO pays VALUES (NULL,'TM', 'Turkménistan');
INSERT INTO pays VALUES (NULL,'TR', 'Turquie');
INSERT INTO pays VALUES (NULL,'TV', 'Tuvalu');
INSERT INTO pays VALUES (NULL,'UA', 'Ukraine');
INSERT INTO pays VALUES (NULL,'UY', 'Uruguay');
INSERT INTO pays VALUES (NULL,'VU', 'Vanuatu');
INSERT INTO pays VALUES (NULL,'VE', 'Venezuela');
INSERT INTO pays VALUES (NULL,'VN', 'Vietnam');
INSERT INTO pays VALUES (NULL,'WF', 'Wallis-et-Futuna');
INSERT INTO pays VALUES (NULL,'YE', 'Yémen');
INSERT INTO pays VALUES (NULL,'ZM', 'Zambie');
INSERT INTO pays VALUES (NULL,'ZW', 'Zimbabwe');